// #include "../src/types.h"

// #include "../src/sync/sleeplock.h"
// #include "../src/fs/file.h"
#include "../src/fs/fs.h"
#include "../src/fcntl.h"
#include "user.h"
// #include <stddef.h>
#include "../src/syscall/syscall.h"

char*
strcpy(char *s, const char *t)
{
  char *os;

  os = s;
  while((*s++ = *t++) != 0)
    ;
  return os;
}

int
strcmp(const char *p, const char *q)
{
  while(*p && *p == *q)
    p++, q++;
  return (uchar)*p - (uchar)*q;
}

uint
strlen(const char *s)
{
  int n;

  for(n = 0; s[n]; n++)
    ;
  return n;
}

void*
memset(void *dst, int c, uint n)
{
  char *cdst = (char *) dst;
  int i;
  for(i = 0; i < n; i++){
    cdst[i] = c;
  }
  return dst;
}

char*
strchr(const char *s, char c)
{
  for(; *s; s++)
    if(*s == c)
      return (char*)s;
  return 0;
}

char*
gets(char *buf, int max)
{
  int i, cc;
  char c;

  for(i=0; i+1 < max; ){
    cc = read(0, &c, 1);
    if(cc < 1)
      break;
    buf[i++] = c;
    if(c == '\n' || c == '\r')
      break;
  }
  buf[i] = '\0';
  return buf;
}

// int
// stat(const char *n, struct stat *st)
// {
//   int fd;
//   int r;

//   fd = open(n, O_RDONLY);
//   if(fd < 0)
//     return -1;
//   r = fstat(fd, st);
//   close(fd);
//   return r;
// }

int
atoi(const char *s)
{
  int n;

  n = 0;
  while('0' <= *s && *s <= '9')
    n = n*10 + *s++ - '0';
  return n;
}

void*
memmove(void *vdst, const void *vsrc, int n)
{
  char *dst;
  const char *src;

  dst = vdst;
  src = vsrc;
  while(n-- > 0)
    *dst++ = *src++;
  return vdst;
}

int fork(void)
{

    return syscall(SYS_clone, 17, 0, 0, 0, 0);
}

int exit(int code)
{
    syscall(SYS_exit, code);    __builtin_unreachable();
}

int waitpid(int pid, int *code, int options)
{
    return syscall(SYS_wait4, pid, code, options, 0);}

int wait(int *code)
{
    return waitpid((int)-1, code, 0);
}


int pipe(int fd[2])
{
    return syscall(SYS_pipe2, fd, 0);
}

int read(int fd, void *buf, int len)
{
    return syscall(SYS_read, fd, buf, len);
}

int write(int fd, const void *buf, int len)
{
    return syscall(SYS_write, fd, buf, len);
}

int close(int fd)
{
    return syscall(SYS_close, fd);
}

int exec(const char *name, char **argv)
{
    return syscall(SYS_execve, name, argv, 0);
}

int execve(const char *name, char *const argv[], char *const argp[])
{
    return syscall(SYS_execve, name, argv, argp);
}

int times(void *mytimes)
{
    return syscall(SYS_times, mytimes);
}

int sleep(int time)
{
    if (syscall(SYS_sleep, time))
        return time;
    return 0;
}

int uptime(void)
{
    return syscall(SYS_uptime);
}

int sched_yield(void)
{
    return syscall(SYS_sched_yield);
}

int mkdir(const char *path)
{
    return syscall(SYS_mkdirat, AT_FDCWD, path, 0);
}

int open(const char *path, int flags)
{
    return syscall(SYS_openat, AT_FDCWD, path, flags, O_RDWR);
}

int socket(int domain, int type, int protocol)
{
  return syscall(SYS_socket, domain, type, protocol);
}

int bind(int sockfd, const struct sockaddr *addr, socklen_t addrlen)
{
  return syscall(SYS_bind, sockfd, addr, addrlen);
}

int connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen)
{
  return syscall(SYS_connect, sockfd, addr, addrlen);
}

ssize_t send(int sockfd, const void *buf, size_t len, int flags)
{
  return syscall(SYS_sendto, sockfd, buf, len, flags, 0, 0);
}

ssize_t sendto(int sockfd, const void *buf, size_t len, int flags,
               const struct sockaddr *dest_addr, socklen_t addrlen)
{
  return syscall(SYS_sendto, sockfd, buf, len, flags, dest_addr, addrlen);
}

ssize_t recv(int sockfd, void *buf, size_t len, int flags)
{
  return syscall(SYS_recvfrom, sockfd, buf, len, flags, 0, 0);
}

ssize_t recvfrom(int sockfd, void *buf, size_t len, int flags,
                 struct sockaddr *src_addr, socklen_t *addrlen)
{
  return syscall(SYS_recvfrom, sockfd, buf, len, flags, src_addr, addrlen);
}

int listen(int sockfd, int backlog)
{
  return syscall(SYS_listen, sockfd, backlog);
}

int accept(int sockfd, struct sockaddr *addr, socklen_t *addrlen)
{
  return syscall(SYS_accept, sockfd, addr, addrlen);
}

int chdir(const char *path)
{
    return syscall(SYS_chdir, path);
}


int getdents64(int fd, struct linux_dirent64 *dirp64, unsigned long len)
{
    return syscall(SYS_getdents64, fd, dirp64, len);
}

int sys_unlinkat(int dirfd, const char *path, int flags)
{
    return syscall(SYS_unlinkat, dirfd, path, flags);
}

int unlink(const char *path)
{
    return sys_unlinkat(AT_FDCWD, path, 0);
}


int getpid(void)
{
    return syscall(SYS_getpid);
}
int dup(int fd)
{
    return syscall(SYS_dup, fd);
}
int shutdown(){
    return syscall(SYS_xv6_shutdown);
}

// xv6 兼容，直接调用系统调用
int mknod(const char *path, short major, short minor) {
  return syscall(SYS_xv6_mknod, path, major, minor);
}

// # generated by usys.pl - do not edit

// .global kill
// kill:
//  li a7, SYS_xv6_kill
//  ecall
//  ret


// .global mknod
// mknod:
//  li a7, SYS_xv6_mknod
//  ecall
//  ret

// .global fstat
// fstat:
//  li a7, SYS_xv6_fstat
//  ecall
//  ret
// .global link
// link:
//  li a7, SYS_xv6_link
//  ecall
//  ret


int fstat(int fd, struct stat *st)
{
    return syscall(SYS_fstat, fd, st);
}

int stat(const char *path, struct stat *st)
{
    return syscall(SYS_fstatat, AT_FDCWD, path, st, 0);
}

long long sbrk(int n)
{
    return syscall(SYS_brk, n);
}

// eventfd implementation
int eventfd(unsigned int initval, int flags)
{
    return syscall(SYS_eventfd2, initval, flags);
}

// .global gettimeofday
// gettimeofday:
//  li a7, SYS_xv6_gettimeofday
//  ecall
//  ret
